INSERT INTO `EMPLOYEES`(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CORPORATE_EMAIL) VALUES (1, 'John', 'Doe', 'john@example.com');
INSERT INTO `EMPLOYEES`(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CORPORATE_EMAIL) VALUES (2, 'Lola', 'Bunny', 'lolabunny@example.com');
INSERT INTO `EMPLOYEES`(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CORPORATE_EMAIL) VALUES (3, 'James', 'Bond', 'james007@example.com');
INSERT INTO `EMPLOYEES`(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CORPORATE_EMAIL) VALUES (4, 'Maxwell', 'Williams', 'maxwell@example.com');
INSERT INTO `EMPLOYEES`(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CORPORATE_EMAIL) VALUES (5, 'Mary', 'Public', 'mary@luv2code.com');